language: cpp

os:
  - linux
  - osx
dist: xenial

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

script:
  - make
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make test; fi
