language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_script: if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

script:
  - make
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make test; fi
